"""User model settings port protocol."""

from __future__ import annotations

from typing import Protocol


class UserModelSettingsPort(Protocol):
    """Port for per-user model gateway configuration."""

    async def get_user_config(self, user_id: str) -> dict: ...

    async def update_user_config(self, user_id: str, config: dict) -> dict: ...

    async def list_channels(self, user_id: str) -> list[dict]: ...

    async def create_channel(self, user_id: str, channel: dict) -> dict: ...

    async def update_channel(self, user_id: str, channel_id: str, channel: dict) -> dict: ...

    async def delete_channel(self, user_id: str, channel_id: str) -> bool: ...

    async def list_model_mappings(self, user_id: str) -> list[dict]: ...

    async def update_model_mappings(self, user_id: str, mappings: list[dict]) -> list[dict]: ...
